package entite;
// Generated 2018-09-17 14:03:04 by Hibernate Tools 4.3.1



/**
 * Bill generated by hbm2java
 */
public class Bill  implements java.io.Serializable {


     private String billNumber;
     private PlacedOrder placedOrder;
     private double finalOrderPrice;

    public Bill() {
    }

    public Bill(String billNumber, PlacedOrder placedOrder, double finalOrderPrice) {
       this.billNumber = billNumber;
       this.placedOrder = placedOrder;
       this.finalOrderPrice = finalOrderPrice;
    }
   
    public String getBillNumber() {
        return this.billNumber;
    }
    
    public void setBillNumber(String billNumber) {
        this.billNumber = billNumber;
    }
    public PlacedOrder getPlacedOrder() {
        return this.placedOrder;
    }
    
    public void setPlacedOrder(PlacedOrder placedOrder) {
        this.placedOrder = placedOrder;
    }
    public double getFinalOrderPrice() {
        return this.finalOrderPrice;
    }
    
    public void setFinalOrderPrice(double finalOrderPrice) {
        this.finalOrderPrice = finalOrderPrice;
    }




}


