package entite;
// Generated 2018-09-14 12:07:09 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Bill generated by hbm2java
 */
public class Bill  implements java.io.Serializable {


     private String billNumber;
     private PlacedOrder placedOrder;
     private BigDecimal finalOrderPrice;

    public Bill() {
    }

    public Bill(String billNumber, PlacedOrder placedOrder, BigDecimal finalOrderPrice) {
       this.billNumber = billNumber;
       this.placedOrder = placedOrder;
       this.finalOrderPrice = finalOrderPrice;
    }
   
    public String getBillNumber() {
        return this.billNumber;
    }
    
    public void setBillNumber(String billNumber) {
        this.billNumber = billNumber;
    }
    public PlacedOrder getPlacedOrder() {
        return this.placedOrder;
    }
    
    public void setPlacedOrder(PlacedOrder placedOrder) {
        this.placedOrder = placedOrder;
    }
    public BigDecimal getFinalOrderPrice() {
        return this.finalOrderPrice;
    }
    
    public void setFinalOrderPrice(BigDecimal finalOrderPrice) {
        this.finalOrderPrice = finalOrderPrice;
    }




}


