package entite;
// Generated Sep 13, 2018 1:59:18 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Bill generated by hbm2java
 */
public class Bill  implements java.io.Serializable {


     private String billNumber;
     private Orders orders;
     private BigDecimal finalOrderPrice;

    public Bill() {
    }

    public Bill(String billNumber, Orders orders, BigDecimal finalOrderPrice) {
       this.billNumber = billNumber;
       this.orders = orders;
       this.finalOrderPrice = finalOrderPrice;
    }
   
    public String getBillNumber() {
        return this.billNumber;
    }
    
    public void setBillNumber(String billNumber) {
        this.billNumber = billNumber;
    }
    public Orders getOrders() {
        return this.orders;
    }
    
    public void setOrders(Orders orders) {
        this.orders = orders;
    }
    public BigDecimal getFinalOrderPrice() {
        return this.finalOrderPrice;
    }
    
    public void setFinalOrderPrice(BigDecimal finalOrderPrice) {
        this.finalOrderPrice = finalOrderPrice;
    }




}


