package entite;
// Generated 2018-09-17 14:03:04 by Hibernate Tools 4.3.1



/**
 * CategoryDetail generated by hbm2java
 */
public class CategoryDetail  implements java.io.Serializable {


     private CategoryDetailId id;
     private Category category;
     private Languages languages;
     private String categoryName;
     private String about;

    public CategoryDetail() {
    }

	
    public CategoryDetail(CategoryDetailId id, Category category, Languages languages, String categoryName) {
        this.id = id;
        this.category = category;
        this.languages = languages;
        this.categoryName = categoryName;
    }
    public CategoryDetail(CategoryDetailId id, Category category, Languages languages, String categoryName, String about) {
       this.id = id;
       this.category = category;
       this.languages = languages;
       this.categoryName = categoryName;
       this.about = about;
    }
   
    public CategoryDetailId getId() {
        return this.id;
    }
    
    public void setId(CategoryDetailId id) {
        this.id = id;
    }
    public Category getCategory() {
        return this.category;
    }
    
    public void setCategory(Category category) {
        this.category = category;
    }
    public Languages getLanguages() {
        return this.languages;
    }
    
    public void setLanguages(Languages languages) {
        this.languages = languages;
    }
    public String getCategoryName() {
        return this.categoryName;
    }
    
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }
    public String getAbout() {
        return this.about;
    }
    
    public void setAbout(String about) {
        this.about = about;
    }




}


