package entite;
// Generated 2018-09-17 14:03:04 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Customer generated by hbm2java
 */
public class Customer  implements java.io.Serializable {


     private String email;
     private String firstName;
     private String lastName;
     private String password;
     private String address;
     private Set placedOrders = new HashSet(0);

    public Customer() {
    }

	
    public Customer(String email, String firstName, String lastName, String password, String address) {
        this.email = email;
        this.firstName = firstName;
        this.lastName = lastName;
        this.password = password;
        this.address = address;
    }
    public Customer(String email, String firstName, String lastName, String password, String address, Set placedOrders) {
       this.email = email;
       this.firstName = firstName;
       this.lastName = lastName;
       this.password = password;
       this.address = address;
       this.placedOrders = placedOrders;
    }
   
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public Set getPlacedOrders() {
        return this.placedOrders;
    }
    
    public void setPlacedOrders(Set placedOrders) {
        this.placedOrders = placedOrders;
    }




}


