package entite;
// Generated Sep 13, 2018 1:59:18 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * DetailId generated by hbm2java
 */
public class DetailId  implements java.io.Serializable {


     private BigDecimal sku;
     private String languageCode;

    public DetailId() {
    }

    public DetailId(BigDecimal sku, String languageCode) {
       this.sku = sku;
       this.languageCode = languageCode;
    }
   
    public BigDecimal getSku() {
        return this.sku;
    }
    
    public void setSku(BigDecimal sku) {
        this.sku = sku;
    }
    public String getLanguageCode() {
        return this.languageCode;
    }
    
    public void setLanguageCode(String languageCode) {
        this.languageCode = languageCode;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DetailId) ) return false;
		 DetailId castOther = ( DetailId ) other; 
         
		 return ( (this.getSku()==castOther.getSku()) || ( this.getSku()!=null && castOther.getSku()!=null && this.getSku().equals(castOther.getSku()) ) )
 && ( (this.getLanguageCode()==castOther.getLanguageCode()) || ( this.getLanguageCode()!=null && castOther.getLanguageCode()!=null && this.getLanguageCode().equals(castOther.getLanguageCode()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getSku() == null ? 0 : this.getSku().hashCode() );
         result = 37 * result + ( getLanguageCode() == null ? 0 : this.getLanguageCode().hashCode() );
         return result;
   }   


}


