package entite;
// Generated 2018-09-14 12:07:09 by Hibernate Tools 4.3.1



/**
 * Detail generated by hbm2java
 */
public class Detail implements java.io.Serializable {


     private DetailId id;
     private Product product;
     private Language language;
     private String type;
     private String keyFeatures;
     private String about;
     private String features;

    public Detail() {
    }

	
    public Detail(DetailId id, Product product, Language language, String type) {
        this.id = id;
        this.product = product;
        this.language = language;
        this.type = type;
    }
    public Detail(DetailId id, Product product, Language language, String type, String keyFeatures, String about, String features) {
       this.id = id;
       this.product = product;
       this.language = language;
       this.type = type;
       this.keyFeatures = keyFeatures;
       this.about = about;
       this.features = features;
    }
   
    public DetailId getId() {
        return this.id;
    }
    
    public void setId(DetailId id) {
        this.id = id;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public Language getLanguage() {
        return this.language;
    }
    
    public void setLanguage(Language language) {
        this.language = language;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getKeyFeatures() {
        return this.keyFeatures;
    }
    
    public void setKeyFeatures(String keyFeatures) {
        this.keyFeatures = keyFeatures;
    }
    public String getAbout() {
        return this.about;
    }
    
    public void setAbout(String about) {
        this.about = about;
    }
    public String getFeatures() {
        return this.features;
    }
    
    public void setFeatures(String features) {
        this.features = features;
    }




}


