package entite;
// Generated Sep 13, 2018 1:59:18 AM by Hibernate Tools 4.3.1



/**
 * Detail generated by hbm2java
 */
public class Detail  implements java.io.Serializable {


     private DetailId id;
     private Languages languages;
     private Product product;
     private String type;
     private String keyFeatures;
     private String about;
     private String features;

    public Detail() {
    }

	
    public Detail(DetailId id, Languages languages, Product product, String type) {
        this.id = id;
        this.languages = languages;
        this.product = product;
        this.type = type;
    }
    public Detail(DetailId id, Languages languages, Product product, String type, String keyFeatures, String about, String features) {
       this.id = id;
       this.languages = languages;
       this.product = product;
       this.type = type;
       this.keyFeatures = keyFeatures;
       this.about = about;
       this.features = features;
    }
   
    public DetailId getId() {
        return this.id;
    }
    
    public void setId(DetailId id) {
        this.id = id;
    }
    public Languages getLanguages() {
        return this.languages;
    }
    
    public void setLanguages(Languages languages) {
        this.languages = languages;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getKeyFeatures() {
        return this.keyFeatures;
    }
    
    public void setKeyFeatures(String keyFeatures) {
        this.keyFeatures = keyFeatures;
    }
    public String getAbout() {
        return this.about;
    }
    
    public void setAbout(String about) {
        this.about = about;
    }
    public String getFeatures() {
        return this.features;
    }
    
    public void setFeatures(String features) {
        this.features = features;
    }




}


