package entite;
// Generated 2018-09-14 12:07:09 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Language generated by hbm2java
 */
public class Language  implements java.io.Serializable {


     private String languageCode;
     private String languageName;
     private String languageImage;
     private Set details = new HashSet(0);

    public Language() {
    }

	
    public Language(String languageCode, String languageName, String languageImage) {
        this.languageCode = languageCode;
        this.languageName = languageName;
        this.languageImage = languageImage;
    }
    public Language(String languageCode, String languageName, String languageImage, Set details) {
       this.languageCode = languageCode;
       this.languageName = languageName;
       this.languageImage = languageImage;
       this.details = details;
    }
   
    public String getLanguageCode() {
        return this.languageCode;
    }
    
    public void setLanguageCode(String languageCode) {
        this.languageCode = languageCode;
    }
    public String getLanguageName() {
        return this.languageName;
    }
    
    public void setLanguageName(String languageName) {
        this.languageName = languageName;
    }
    public String getLanguageImage() {
        return this.languageImage;
    }
    
    public void setLanguageImage(String languageImage) {
        this.languageImage = languageImage;
    }
    public Set getDetails() {
        return this.details;
    }
    
    public void setDetails(Set details) {
        this.details = details;
    }




}


