package entite;
// Generated 2018-09-17 14:03:04 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Languages generated by hbm2java
 */
public class Languages  implements java.io.Serializable {


     private String languageCode;
     private String languageName;
     private String languageImage;
     private Set productDetails = new HashSet(0);
     private Set categoryDetails = new HashSet(0);

    public Languages() {
    }

	
    public Languages(String languageCode, String languageName, String languageImage) {
        this.languageCode = languageCode;
        this.languageName = languageName;
        this.languageImage = languageImage;
    }
    public Languages(String languageCode, String languageName, String languageImage, Set productDetails, Set categoryDetails) {
       this.languageCode = languageCode;
       this.languageName = languageName;
       this.languageImage = languageImage;
       this.productDetails = productDetails;
       this.categoryDetails = categoryDetails;
    }
   
    public String getLanguageCode() {
        return this.languageCode;
    }
    
    public void setLanguageCode(String languageCode) {
        this.languageCode = languageCode;
    }
    public String getLanguageName() {
        return this.languageName;
    }
    
    public void setLanguageName(String languageName) {
        this.languageName = languageName;
    }
    public String getLanguageImage() {
        return this.languageImage;
    }
    
    public void setLanguageImage(String languageImage) {
        this.languageImage = languageImage;
    }
    public Set getProductDetails() {
        return this.productDetails;
    }
    
    public void setProductDetails(Set productDetails) {
        this.productDetails = productDetails;
    }
    public Set getCategoryDetails() {
        return this.categoryDetails;
    }
    
    public void setCategoryDetails(Set categoryDetails) {
        this.categoryDetails = categoryDetails;
    }




}


