package entite;
// Generated Sep 13, 2018 1:59:18 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * OrderLinesId generated by hbm2java
 */
public class OrderLinesId  implements java.io.Serializable {


     private BigDecimal sku;
     private String orderNumber;

    public OrderLinesId() {
    }

    public OrderLinesId(BigDecimal sku, String orderNumber) {
       this.sku = sku;
       this.orderNumber = orderNumber;
    }
   
    public BigDecimal getSku() {
        return this.sku;
    }
    
    public void setSku(BigDecimal sku) {
        this.sku = sku;
    }
    public String getOrderNumber() {
        return this.orderNumber;
    }
    
    public void setOrderNumber(String orderNumber) {
        this.orderNumber = orderNumber;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof OrderLinesId) ) return false;
		 OrderLinesId castOther = ( OrderLinesId ) other; 
         
		 return ( (this.getSku()==castOther.getSku()) || ( this.getSku()!=null && castOther.getSku()!=null && this.getSku().equals(castOther.getSku()) ) )
 && ( (this.getOrderNumber()==castOther.getOrderNumber()) || ( this.getOrderNumber()!=null && castOther.getOrderNumber()!=null && this.getOrderNumber().equals(castOther.getOrderNumber()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getSku() == null ? 0 : this.getSku().hashCode() );
         result = 37 * result + ( getOrderNumber() == null ? 0 : this.getOrderNumber().hashCode() );
         return result;
   }   


}


