package entite;
// Generated 2018-09-14 20:08:41 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * OrderLine generated by hbm2java
 */
public class OrderLine  implements java.io.Serializable {


     private OrderLineId id;
     private Product product;
     private PlacedOrder placedOrder;
     private BigDecimal quantity;
     private BigDecimal prix;

    public OrderLine() {
    }

    public OrderLine(OrderLineId id, Product product, PlacedOrder placedOrder, BigDecimal quantity, BigDecimal prix) {
       this.id = id;
       this.product = product;
       this.placedOrder = placedOrder;
       this.quantity = quantity;
       this.prix = prix;
    }
   
    public OrderLineId getId() {
        return this.id;
    }
    
    public void setId(OrderLineId id) {
        this.id = id;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public PlacedOrder getPlacedOrder() {
        return this.placedOrder;
    }
    
    public void setPlacedOrder(PlacedOrder placedOrder) {
        this.placedOrder = placedOrder;
    }
    public BigDecimal getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(BigDecimal quantity) {
        this.quantity = quantity;
    }
    public BigDecimal getPrix() {
        return this.prix;
    }
    
    public void setPrix(BigDecimal prix) {
        this.prix = prix;
    }




}


