package entite;
// Generated Sep 13, 2018 1:59:18 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * OrderLines generated by hbm2java
 */
public class OrderLines  implements java.io.Serializable {


     private OrderLinesId id;
     private Product product;
     private Orders orders;
     private BigDecimal quantity;
     private BigDecimal prix;

    public OrderLines() {
    }

    public OrderLines(OrderLinesId id, Product product, Orders orders, BigDecimal quantity, BigDecimal prix) {
       this.id = id;
       this.product = product;
       this.orders = orders;
       this.quantity = quantity;
       this.prix = prix;
    }
   
    public OrderLinesId getId() {
        return this.id;
    }
    
    public void setId(OrderLinesId id) {
        this.id = id;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public Orders getOrders() {
        return this.orders;
    }
    
    public void setOrders(Orders orders) {
        this.orders = orders;
    }
    public BigDecimal getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(BigDecimal quantity) {
        this.quantity = quantity;
    }
    public BigDecimal getPrix() {
        return this.prix;
    }
    
    public void setPrix(BigDecimal prix) {
        this.prix = prix;
    }




}


