package entite;
// Generated Sep 13, 2018 1:59:18 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Orders generated by hbm2java
 */
public class Orders  implements java.io.Serializable {


     private String orderNumber;
     private Costumer costumer;
     private String status;
     private Set orderLineses = new HashSet(0);
     private Set payments = new HashSet(0);
     private Set bills = new HashSet(0);

    public Orders() {
    }

	
    public Orders(String orderNumber, Costumer costumer) {
        this.orderNumber = orderNumber;
        this.costumer = costumer;
    }
    public Orders(String orderNumber, Costumer costumer, String status, Set orderLineses, Set payments, Set bills) {
       this.orderNumber = orderNumber;
       this.costumer = costumer;
       this.status = status;
       this.orderLineses = orderLineses;
       this.payments = payments;
       this.bills = bills;
    }
   
    public String getOrderNumber() {
        return this.orderNumber;
    }
    
    public void setOrderNumber(String orderNumber) {
        this.orderNumber = orderNumber;
    }
    public Costumer getCostumer() {
        return this.costumer;
    }
    
    public void setCostumer(Costumer costumer) {
        this.costumer = costumer;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Set getOrderLineses() {
        return this.orderLineses;
    }
    
    public void setOrderLineses(Set orderLineses) {
        this.orderLineses = orderLineses;
    }
    public Set getPayments() {
        return this.payments;
    }
    
    public void setPayments(Set payments) {
        this.payments = payments;
    }
    public Set getBills() {
        return this.bills;
    }
    
    public void setBills(Set bills) {
        this.bills = bills;
    }




}


