package entite;
// Generated 2018-09-17 14:03:04 by Hibernate Tools 4.3.1



/**
 * Payment generated by hbm2java
 */
public class Payment  implements java.io.Serializable {


     private String paymentMode;
     private PlacedOrder placedOrder;

    public Payment() {
    }

    public Payment(String paymentMode, PlacedOrder placedOrder) {
       this.paymentMode = paymentMode;
       this.placedOrder = placedOrder;
    }
   
    public String getPaymentMode() {
        return this.paymentMode;
    }
    
    public void setPaymentMode(String paymentMode) {
        this.paymentMode = paymentMode;
    }
    public PlacedOrder getPlacedOrder() {
        return this.placedOrder;
    }
    
    public void setPlacedOrder(PlacedOrder placedOrder) {
        this.placedOrder = placedOrder;
    }




}


