package entite;
// Generated Sep 13, 2018 1:59:18 AM by Hibernate Tools 4.3.1



/**
 * Payment generated by hbm2java
 */
public class Payment  implements java.io.Serializable {


     private String paymentMode;
     private Orders orders;

    public Payment() {
    }

    public Payment(String paymentMode, Orders orders) {
       this.paymentMode = paymentMode;
       this.orders = orders;
    }
   
    public String getPaymentMode() {
        return this.paymentMode;
    }
    
    public void setPaymentMode(String paymentMode) {
        this.paymentMode = paymentMode;
    }
    public Orders getOrders() {
        return this.orders;
    }
    
    public void setOrders(Orders orders) {
        this.orders = orders;
    }




}


