package entite;
// Generated 2018-09-17 14:03:04 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * PlacedOrder generated by hbm2java
 */
public class PlacedOrder  implements java.io.Serializable {


     private String orderNumber;
     private Customer customer;
     private String status;
     private Set payments = new HashSet(0);
     private Set bills = new HashSet(0);
     private Set orderLines = new HashSet(0);

    public PlacedOrder() {
    }

	
    public PlacedOrder(String orderNumber, Customer customer) {
        this.orderNumber = orderNumber;
        this.customer = customer;
    }
    public PlacedOrder(String orderNumber, Customer customer, String status, Set payments, Set bills, Set orderLines) {
       this.orderNumber = orderNumber;
       this.customer = customer;
       this.status = status;
       this.payments = payments;
       this.bills = bills;
       this.orderLines = orderLines;
    }
   
    public String getOrderNumber() {
        return this.orderNumber;
    }
    
    public void setOrderNumber(String orderNumber) {
        this.orderNumber = orderNumber;
    }
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Set getPayments() {
        return this.payments;
    }
    
    public void setPayments(Set payments) {
        this.payments = payments;
    }
    public Set getBills() {
        return this.bills;
    }
    
    public void setBills(Set bills) {
        this.bills = bills;
    }
    public Set getOrderLines() {
        return this.orderLines;
    }
    
    public void setOrderLines(Set orderLines) {
        this.orderLines = orderLines;
    }




}


