package entite;
// Generated 2018-09-14 12:07:09 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Product generated by hbm2java
 */
public class Product  implements java.io.Serializable {


     private BigDecimal sku;
     private String name;
     private String brand;
     private BigDecimal price;
     private BigDecimal warranty;
     private BigDecimal quantity;
     private String image;
     private Set details = new HashSet(0);
     private Set orderLines = new HashSet(0);

    public Product() {
    }

	
    public Product(BigDecimal sku, String name, String brand, BigDecimal price, BigDecimal quantity, String image) {
        this.sku = sku;
        this.name = name;
        this.brand = brand;
        this.price = price;
        this.quantity = quantity;
        this.image = image;
    }
    public Product(BigDecimal sku, String name, String brand, BigDecimal price, BigDecimal warranty, BigDecimal quantity, String image, Set details, Set orderLines) {
       this.sku = sku;
       this.name = name;
       this.brand = brand;
       this.price = price;
       this.warranty = warranty;
       this.quantity = quantity;
       this.image = image;
       this.details = details;
       this.orderLines = orderLines;
    }
   
    public BigDecimal getSku() {
        return this.sku;
    }
    
    public void setSku(BigDecimal sku) {
        this.sku = sku;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getBrand() {
        return this.brand;
    }
    
    public void setBrand(String brand) {
        this.brand = brand;
    }
    public BigDecimal getPrice() {
        return this.price;
    }
    
    public void setPrice(BigDecimal price) {
        this.price = price;
    }
    public BigDecimal getWarranty() {
        return this.warranty;
    }
    
    public void setWarranty(BigDecimal warranty) {
        this.warranty = warranty;
    }
    public BigDecimal getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(BigDecimal quantity) {
        this.quantity = quantity;
    }
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }
    public Set getDetails() {
        return this.details;
    }
    
    public void setDetails(Set details) {
        this.details = details;
    }
    public Set getOrderLines() {
        return this.orderLines;
    }
    
    public void setOrderLines(Set orderLines) {
        this.orderLines = orderLines;
    }




}


