package entite;
// Generated 2018-09-14 20:08:41 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Product generated by hbm2java
 */
public class Product  implements java.io.Serializable {


     private BigDecimal sku;
     private Category category;
     private String name;
     private String brand;
     private BigDecimal price;
     private BigDecimal quantity;
     private String image;
     private Set orderLines = new HashSet(0);
     private Set productDetails = new HashSet(0);

    public Product() {
    }

	
    public Product(BigDecimal sku, Category category, String name, String brand, BigDecimal price, BigDecimal quantity, String image) {
        this.sku = sku;
        this.category = category;
        this.name = name;
        this.brand = brand;
        this.price = price;
        this.quantity = quantity;
        this.image = image;
    }
    public Product(BigDecimal sku, Category category, String name, String brand, BigDecimal price, BigDecimal quantity, String image, Set orderLines, Set productDetails) {
       this.sku = sku;
       this.category = category;
       this.name = name;
       this.brand = brand;
       this.price = price;
       this.quantity = quantity;
       this.image = image;
       this.orderLines = orderLines;
       this.productDetails = productDetails;
    }
   
    public BigDecimal getSku() {
        return this.sku;
    }
    
    public void setSku(BigDecimal sku) {
        this.sku = sku;
    }
    public Category getCategory() {
        return this.category;
    }
    
    public void setCategory(Category category) {
        this.category = category;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getBrand() {
        return this.brand;
    }
    
    public void setBrand(String brand) {
        this.brand = brand;
    }
    public BigDecimal getPrice() {
        return this.price;
    }
    
    public void setPrice(BigDecimal price) {
        this.price = price;
    }
    public BigDecimal getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(BigDecimal quantity) {
        this.quantity = quantity;
    }
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }
    public Set getOrderLines() {
        return this.orderLines;
    }
    
    public void setOrderLines(Set orderLines) {
        this.orderLines = orderLines;
    }
    public Set getProductDetails() {
        return this.productDetails;
    }
    
    public void setProductDetails(Set productDetails) {
        this.productDetails = productDetails;
    }




}


